version: '3.8'
services:
  litedms:
    image: ${IMAGE_HUB-ghcr.io/prantlf/}litedms
    # environment:
    #   DEBUG: '*'
    ports:
      - 8020:8020
    volumes:
      - ./storage:/storage
    healthcheck:
      test: ["CMD", "/healthchk", "-m", "HEAD", "http://localhost:8020/ping"]
      interval: 60s
      timeout: 20s
      start_period: 20s
      start_interval: 2s
      retries: 3
    restart: unless-stopped
