name: Build and Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: prantlf/setup-v-action@v2

    - uses: prantlf/bump-version-action@v2
      if: github.ref_name == 'master'
      id: bump
      with:
        bump-files: src/config/opts.v

    - run: make check

    - uses: docker/metadata-action@v5
      if: steps.bump.outputs.bumped == 'true'
      id: meta
      with:
        images: |
          ghcr.io/prantlf/litedms
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - uses: docker/login-action@v3
      if: steps.bump.outputs.bumped == 'true'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v5
      if: steps.bump.outputs.bumped == 'true'
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - uses: docker/build-push-action@v5
      if: steps.bump.outputs.bumped != 'true'
      with:
        push: false

    - uses: prantlf/finish-release-action@v1
      if: steps.bump.outputs.bumped == 'true'
      with:
        no-node: true
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
